- name: facts
  hosts: target2
  tasks:
  - name: facts calling
    setup:
  - name: facts print
    debug:
      msg: |
        "the ansible distribution is {{ansible_distribution}}"
        "the ansible kernel is {{ansible_kernel}}"
        "the ansible architecture is {{ansible_architecture}}"
        "the ansible os family is {{ansible_os_family}}"
        "the ansible processor is {{ansible_processor}}"

