- name: intsall
  hosts: target3
  tasks:
  - name: install
    package:
      name: nginx
      state: present
  - name: enable and start
    service:
      name: nginx
      enabled: yes
      state: started
  - name: content add
    copy:
      content: 'who are you'
      dest: /var/www/html/index.html
    notify: restart nginx
  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
