- name: httpd playbook
  hosts: target1
  tasks:
  - name: installation
    dnf:
      name: httpd
      state: present
  - name: enable and start
    service:
      name: httpd
      enabled: yes
      state: started
