- name: nginxplaybook
  hosts: target2
  tasks:
  - name: installation
    dnf:
      name: nginx
      state: present
  - name: enable and start
    service:
      name: nginx
      enabled: yes
      state: started
